package com.example.traodoimathangthoitrang.config;
import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;
public class SecurityInit extends AbstractSecurityWebApplicationInitializer { }